// aprendiendovue/src/components/Pelicula.vue
<template>
  <article class="article-item">
        <div class="image-wrap">
          <img
            :src="pelicula.image"
            :alt="pelicula.title"
            :title="pelicula.title"
          />
        </div>

        <h2>{{pelicula.title}}</h2>
        <span class="date" :class="{
          yearGreen: pelicula.year >= 2016,
          yearRed: pelicula.year < 2016
        }"> {{pelicula.year}} </span>
        <a href="#">Leer más</a>
        <button
          @click="pasarFavoritaAlPadre(pelicula)"
        >Marcar como favorita</button>
        <div class="clearfix"></div>
      </article>
</template>

<script>
export default {
    name: 'Pelicula',
    props: ['pelicula'],
    methods: {
      pasarFavoritaAlPadre(pelicula){
        this.$emit('favorita', pelicula);
        }
    },
}
</script>

// AprendiendoAngular/src/app/components/pelicula/pelicula.component.ts
import { Component, Input, OnInit, Output, EventEmitter } from '@angular/core';
import { Pelicula } from '../../models/pelicula';


@Component({
  selector: 'app-pelicula',
  templateUrl: './pelicula.component.html',
  styleUrls: ['./pelicula.component.css']
})
export class PeliculaComponent implements OnInit {

  @Input() pelicula: Pelicula;
  @Output() marcarFavorita = new EventEmitter();

  constructor() { }

  ngOnInit(): void {
  }

  seleccionar(event, pelicula){
    this.marcarFavorita.emit({pelicula});
  }


}

<article class="article-item">
    <div class="image-wrap">
        <img src="{{pelicula.image}}" alt="{{pelicula.title}}" />
    </div>

    <h2>{{pelicula.title}}</h2>
    <!-- <span class="year" [style.background]="pelicula.year > 2015 ? 'green' : 'red'">
{{pelicula.year}}
</span> -->

    <!-- <span class="year" [class.year-green]="pelicula.year > 2015"
               [class.year-red]="pelicula.year <= 2015">
{{pelicula.year}}
</span> -->

    <span class="year" [ngClass]="{
            'year-green': pelicula.year > 2015,
            'year-red': pelicula.year <= 2015
            }">
        {{pelicula.year}}
    </span>

    <a href="#">Leer más</a>

    <button (click)="seleccionar($event, pelicula)"> 
        Seleccionar como favorita</button>
    <div class="clearfix"></div>
</article>
