// aprendiendovue/src/components/Article.vue
<template>
  <div class="general">
    <Slider texto="Blog"></Slider>
    <div class="center">
      <section id="content">
        <article class="article-item article-detail" v-if="article">
          <div class="image-wrap" v-if="article.image">
            <img
              :src="url + 'get-image/' + article.image"
              alt="article.title"
            />
          </div>

          <h1 class="subheader">{{ article.title }}</h1>
          <span class="date"> {{ article.date | moment("from", "now") }} </span>
          <p>
            {{ article.content }}
          </p>
          <div class="clearfix"></div>

          <router-link :to="'/editar/' + article._id" class="btn btn-warning"
            >Editar</router-link
          >
          <a @click="deleteArticle(article._id)" class="btn btn-danger"
            >Eliminar</a
          >
        </article>
      </section>
      <Sidebar></Sidebar>
      <div class="clearfix"></div>
    </div>
  </div>
</template>

<script>
import Slider from "./Slider";
import Sidebar from "./Sidebar";
import axios from "axios";
import Global from "../Global.js";
import swal from "sweetalert";

export default {
  name: "Article",
  components: {
    Slider,
    Sidebar,
  },
  data() {
    return {
      url: Global.url,
      article: null,
    };
  },
  mounted() {
    let id = this.$route.params.id;
    this.getArticle(id);
  },
  methods: {
    getArticle(articleId) {
      axios.get(this.url + "article/" + articleId).then((res) => {
        if (res.data.status == "success") {
          this.article = res.data.article;
        }
      });
    },
    deleteArticle(articleId) {
      swal({
        title: "Estas seguro?",
        text: "Una vez que sea borrado, no se podrá recuperar",
        icon: "warning",
        buttons: ["Cancelar", "Aceptar"],
        dangerMode: true,
      }).then((willDelete) => {
        if (willDelete) {
          axios.delete(this.url + "article/" + articleId).then((res) => {
            this.article = res.data.article;
            swal(
              "Articulo borrado",
              "El articulo ha sido borrado correctamente",
              "success"
            );
            this.$router.push("/blog");
          });
        } else {
          swal("Tranquilo", "El articulo esta seguro", "success");
        }
      });
    },
  },
};
</script>

// AprendiendoAngular/src/app/components/article/article.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { Global } from '../../services/global';
import { ArticleService } from '../../services/article.service';
import { Article } from '../../models/article';
import  swal from "sweetalert";

@Component({
  selector: 'app-article',
  templateUrl: './article.component.html',
  styleUrls: ['./article.component.css'],
  providers: [ArticleService]
})
export class ArticleComponent implements OnInit {

  public article = Article;
  public url: string;

  constructor(
    private _articleService: ArticleService,
    private _route: ActivatedRoute,
    private _router: Router
    ) {
    this.url = Global.url;
    
  }

  ngOnInit() {

    this._route.params.subscribe(params => {
      let id = params['id'];

      this._articleService.getArticle(id).subscribe(
        response => {
          if (response.article) {
            this.article = response.article;
            console.log(this.article);
          } else {
            this._router.navigate(['/home']);
          }
        },
        error => {
          console.log(error);
          this._router.navigate(['/home']);
        }
      )
    });

  }

  delete(id){

    swal({
      title: "Estas seguro?",
      text: "Una vez que sea borrado, no se podrá recuperar",
      icon: "warning",
      buttons: ['Cancelar', 'Aceptar'],
      dangerMode: true,
    })
      .then((willDelete) => {
        if (willDelete) {

          this._articleService.delete(id).subscribe(
            response => {
              swal("El articulo ha sido eliminado!", {
                icon: "success",
              });
              this._router.navigate(['/blog']);
            },
            error => {
              console.log(error);
              this._router.navigate(['/blog']);
            }
          );
        } else {
          swal("Su articulo esta seguro");
        }
      });

    
  }

}

<div class="center">
    <section id="content">
        <h2 class="subheader">Detalle</h2>
        <article class="article-item article-detail" *ngIf="article">
            <div class="image-wrap">
                <img src="{{url+ 'get-image/' + article.image}}" alt="{{article.title}}" *ngIf="article.image" />
                <img src="../../../assets/images/default.svg" alt="{{article.title}}" *ngIf="!article.image" />
            </div>

            <h1 class="subheader">{{article.title}}</h1>
            <span class="date">
                {{article.date | amLocale: 'es' | amTimeAgo}}
            </span>
            <p>
                {{article.content}}
            </p>

            <div class="buttons">
                <a [routerLink]="['/blog/editar', article._id]" class="btn btn-warning">Editar</a>
                <a (click)="delete(article._id)" class="btn btn-danger">Borrar</a>
            </div>

            <div class="clearfix"></div>
        </article>

    </section>
    <app-sidebar></app-sidebar>
</div>
