// aprendiendovue/src/components/Articles.vue
<template>
  <section id="component-articulo">
    <div id="article-list" v-if="articles && articles.length > 0">
      <article
        class="article-item"
        v-for="article in articles"
        :key="article._id"
      >
        <div class="image-wrap">
          <img
            :src="url + 'get-image/' + article.image"
            alt="article.title"
            v-if="article.image"
          />
          <img
            src="../assets/images/default.svg"
            alt="article.title"
            v-if="!article.image"
          />
        </div>

        <h2>{{ article.title }}</h2>
        <span class="date"> {{ article.date | moment('from', 'now') }} </span>
        <router-link :to="{name: 'article', params:{ id: article._id}}">Leer mas</router-link>

        <div class="clearfix"></div>
      </article>
    </div>
    <div v-else-if="articles && articles.length == 0">
      no hay articulos para mostrar
    </div>
     <div v-else>
        Cargando ...
      </div>
  </section>
</template>

<script>
import Global from "../Global.js";

export default {
  name: "Articles",
  props: ["articles"],
  data() {
    return {
      url: Global.url,
    };
  },
};
</script>

// AprendiendoAngular/src/app/components/articles/articles.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Article } from '../../models/article';
import { Global } from '../../services/global';

@Component({
  selector: 'app-articles',
  templateUrl: './articles.component.html',
  styleUrls: ['./articles.component.css']
})
export class ArticlesComponent implements OnInit {

  @Input() articles: Article[];
  public url: string;
  constructor() {
    this.url = Global.url;
  }

  ngOnInit(): void {
  }

}

<div class="loading" *ngIf="!articles">
    cargando ...
</div>

<div class="loading" *ngIf="articles && articles.length == 0">
    no hay articulos para mostrar, intentalo mas tarde
</div>

<div id="articles" *ngIf="articles">
    <article class="article-item" *ngFor="let article of articles">
        <div class="image-wrap">
            <img src="{{url+ 'get-image/' + article.image}}" alt="{{article.title}}" *ngIf="article.image" />
            <img src="../../../assets/images/default.svg" alt="{{article.title}}" *ngIf="!article.image" />
        </div>

        <h2>{{article.title}}</h2>
        <span class="date">
            {{article.date | amLocale: 'es' | amTimeAgo}}
        </span>
        <a [routerLink]="['/blog/article', article._id]">Leer más</a>

        <div class="clearfix"></div>
    </article>
</div>
